### ISSUE TITLE
Delta Beer Labs

### ISSUE THREAD

**Issue by Sovelond** [myelinviolin/NineSpringsBlog#8]
Create entry for Delta Beer Labs in 'businesses' section
https://www.delta.beer/

**Comment by Yashh56** [comment]
What will be the category? @myelinviolin

**Comment by myelinviolin** [comment]
Restaurant I think would be the best

**Comment by Yashh56** [comment]
What Should be the description? @myelinviolin

**Comment by myelinviolin** [comment]
Just copy what they have on the website
